name: Java CI
on: push
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/checkout@v2
        name: my-step
      - uses: actions/upload-artifact@v2
        with:
          name: upload 
          path: .
  Test:
    runs-on: ubuntu-latest
    needs: Clone-down
    container: gradle:6-jdk11
    steps:
    - name: Download code
      uses: actions/download-artifact@v2
      with:
        name: code
        path: .
    - run: ci/unit-test-app.sh
      name: my-test
  Build:
    runs-on: ubuntu-latest
    needs: Clone-down
    container: gradle:6-jdk11
    steps:
    - name: Download
      uses: actions/download-artifact@v2
      with:
        name: code
        path: .
    - name: Build
      run: chmod +x ci/build-app.sh && ci/build-app.sh
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: code
        path: .
