name: Java CI
on: push
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/checkout@v2
        name: my-step
      - uses: actions/upload-artifact@v2
        with:
          name: upload repo
          path: .
  Test:
    runs-on: ubuntu-latest
    needs: Clone-down
    container: gradle:6-jdk11
    steps:
    - run: ci/unit-test-app.sh
    name: my-test
  Build:
    runs-on: ubuntu-latest
    needs: Clone-down
    container: gradle:6-jdk11
    steps:
      - run: ci/build-app.sh && chmod +x ci/build-app.sh
